name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build --no-cache --tag=server .
